language: node_js
os:
  - linux
dist: xenial
version: "~> 1.0"
node_js:
  - "6.17"
  - "8.17"
  - "10.19"
  - "11.15"
  - "12.16"
  - "13.10"
before_install:
  - nvm install-latest-npm
  - case "${TRAVIS_NODE_VERSION}" in 0.*) export NPM_CONFIG_STRICT_SSL=false ;; esac
install:
  - if [ "${TRAVIS_NODE_VERSION}" = "0.6" ] || [ "${TRAVIS_NODE_VERSION}" = "0.9"
    ]; then nvm install --latest-npm 0.8 && npm install && nvm use "${TRAVIS_NODE_VERSION}";
    else npm install; fi;
script:
  - if [ -n "${PRETEST-}" ]; then npm run pretest ; fi
  - if [ -n "${TEST-}" ]; then npm run tests-only ; fi
env:
    jobs:
      - TEST: "true"
